In [3]:
from pjs_qlab.data.YahooPriceFetcher import YahooPriceFetcher as price_fetcher

In [4]:
from pypfopt import HRPOpt
from pypfopt import expected_returns

In [21]:
import pandas as pd

In [5]:
tickers=['NUE','COST','UNH','ORCL','LLY','DE','CAT','BRK-B','AVGO','ABBV']

In [10]:
yObj=price_fetcher(tickers,period='2y')

In [11]:
closes=yObj.get_close()

[*********************100%***********************]  10 of 10 completed

In [12]:
returns=expected_returns.returns_from_prices(closes)

In [13]:
returns

Ticker,ABBV,AVGO,BRK-B,CAT,COST,DE,LLY,NUE,ORCL,UNH
Date,,,,,,,,,,
2024-03-26,0.003697,-0.014864,0.004025,0.001236,0.000027,0.001231,0.002276,-0.007264,0.003093,0.013234
2024-03-27,0.006473,-0.009583,0.013023,0.023177,0.001505,0.030450,0.004233,0.026044,-0.009488,0.001605
2024-03-28,0.009704,0.005065,0.008611,0.004882,0.000751,0.003911,-0.000283,-0.003324,0.002714,0.003245
2024-04-01,-0.007359,0.018749,-0.000761,-0.007341,-0.015547,-0.016068,-0.022379,0.010611,-0.001035,-0.010107
2024-04-02,-0.000387,-0.008517,-0.003046,0.002997,-0.013782,-0.000346,0.004484,-0.008150,-0.009085,-0.064448
...,...,...,...,...,...,...,...,...,...,...
2026-03-18,-0.051966,-0.016744,-0.016464,-0.011937,-0.016303,-0.005642,-0.013221,-0.005676,-0.011572,-0.011267
2026-03-19,-0.010128,0.012376,-0.006172,-0.007165,-0.005245,-0.006024,-0.000599,0.004902,0.017135,-0.013681
2026-03-20,-0.005625,-0.029171,-0.001122,-0.011283,-0.002513,-0.013831,-0.011771,-0.020809,-0.037552,-0.017294
2026-03-23,-0.000683,0.038646,-0.001996,0.030578,-0.006788,0.016615,0.004246,0.012864,0.031133,-0.021953
2026-03-24,-0.001440,-0.012992,0.001604,0.019674,0.009919,0.020878,-0.010300,0.008561,-0.044415,0.004804

In [16]:
hrp=HRPOpt(returns)
hrp.optimize()

OrderedDict([('ABBV', np.float64(0.1446423973498767)),
             ('AVGO', np.float64(0.017716703765440756)),
             ('BRK-B', np.float64(0.2589184336510152)),
             ('CAT', np.float64(0.06935061654834956)),
             ('COST', np.float64(0.19012000873087545)),
             ('DE', np.float64(0.08412163305712428)),
             ('LLY', np.float64(0.08658378587503075)),
             ('NUE', np.float64(0.05983355510337874)),
             ('ORCL', np.float64(0.019245744368541488)),
             ('UNH', np.float64(0.06946712155036706))])

In [19]:
weights=hrp.clean_weights()
weights

OrderedDict([('ABBV', 0.14464),
             ('AVGO', 0.01772),
             ('BRK-B', 0.25892),
             ('CAT', 0.06935),
             ('COST', 0.19012),
             ('DE', 0.08412),
             ('LLY', 0.08658),
             ('NUE', 0.05983),
             ('ORCL', 0.01925),
             ('UNH', 0.06947)])

In [23]:
portfolio_values=closes.dot(pd.Series(weights))
portfolio_values

Date
2024-03-25    438.631166
2024-03-26    439.688862
2024-03-27    443.569888
2024-03-28    445.157650
2024-04-01    440.372916
                 ...
2026-03-18    555.433387
2026-03-19    552.591911
2026-03-20    548.867951
2026-03-23    549.907963
2026-03-24    552.996584
Length: 501, dtype: float64

In [27]:
weights_df=pd.DataFrame(list(weights.items()),columns=['ticker','weight'])
weights_df

  ticker   weight
0   ABBV  0.14464
1   AVGO  0.01772
2  BRK-B  0.25892
3    CAT  0.06935
4   COST  0.19012
5     DE  0.08412
6    LLY  0.08658
7    NUE  0.05983
8   ORCL  0.01925
9    UNH  0.06947